* riak_core
** Overview
Riak Core is an open source Erlang library that helps you build distributed, scalable, fault-tolerant
applications. Riak Core is influenced by the [[http://s3.amazonaws.com/AllThingsDistributed/sosp/amazon-dynamo-sosp2007.pdf][Amazon Dynamo Paper]] and [[http://portal.acm.org/citation.cfm?doid=564585.564601][CAP Theorem]].

** Quick Start
   You must have [[http://erlang.org/download.html][Erlang/OTP R13B04]] or later and a GNU-style build
   system to compile and run =riak_core=. The easiest way to utilize riak_core is by installing the full 
   Riak application available on [[https://github.com/basho/riak][Github]].

** Contributing
   We encourage contributions to =riak_core= from the community.

   1) Fork the =riak_core= repository on [[https://github.com/basho/riak_core][Github]].
   2) Clone your fork or add the remote if you already have a clone of
      the repository.
#+BEGIN_SRC shell
git clone git@github.com:yourusername/riak_core.git
# or
git remote add mine git@github.com:yourusername/riak_core.git
#+END_SRC
   3) Create a topic branch for your change.
#+BEGIN_SRC shell
git checkout -b some-topic-branch
#+END_SRC
   4) Make your change and commit. Use a clear and descriptive commit
      message, spanning multiple lines if detailed explanation is
      needed.
   5) Push to your fork of the repository and then send a pull-request
      through Github.
#+BEGIN_SRC shell
git push mine some-topic-branch
#+END_SRC
   6) A Basho engineer or community maintainer will review your patch
      and merge it into the main repository or send you feedback.
